/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package otpDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SignupOTP service. Represents a row in the &quot;a_SignupOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>otpDB.model.impl.SignupOTPModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>otpDB.model.impl.SignupOTPImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SignupOTP
 * @generated
 */
@ProviderType
public interface SignupOTPModel
	extends BaseModel<SignupOTP>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a signup otp model instance should use the {@link SignupOTP} interface instead.
	 */

	/**
	 * Returns the primary key of this signup otp.
	 *
	 * @return the primary key of this signup otp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this signup otp.
	 *
	 * @param primaryKey the primary key of this signup otp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this signup otp.
	 *
	 * @return the uuid of this signup otp
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this signup otp.
	 *
	 * @param uuid the uuid of this signup otp
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the signup otp ID of this signup otp.
	 *
	 * @return the signup otp ID of this signup otp
	 */
	public long getSignupOTPId();

	/**
	 * Sets the signup otp ID of this signup otp.
	 *
	 * @param signupOTPId the signup otp ID of this signup otp
	 */
	public void setSignupOTPId(long signupOTPId);

	/**
	 * Returns the group ID of this signup otp.
	 *
	 * @return the group ID of this signup otp
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this signup otp.
	 *
	 * @param groupId the group ID of this signup otp
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this signup otp.
	 *
	 * @return the company ID of this signup otp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this signup otp.
	 *
	 * @param companyId the company ID of this signup otp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this signup otp.
	 *
	 * @return the user ID of this signup otp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this signup otp.
	 *
	 * @param userId the user ID of this signup otp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this signup otp.
	 *
	 * @return the user uuid of this signup otp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this signup otp.
	 *
	 * @param userUuid the user uuid of this signup otp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this signup otp.
	 *
	 * @return the user name of this signup otp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this signup otp.
	 *
	 * @param userName the user name of this signup otp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this signup otp.
	 *
	 * @return the create date of this signup otp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this signup otp.
	 *
	 * @param createDate the create date of this signup otp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this signup otp.
	 *
	 * @return the modified date of this signup otp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this signup otp.
	 *
	 * @param modifiedDate the modified date of this signup otp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user email of this signup otp.
	 *
	 * @return the user email of this signup otp
	 */
	@AutoEscape
	public String getUserEmail();

	/**
	 * Sets the user email of this signup otp.
	 *
	 * @param userEmail the user email of this signup otp
	 */
	public void setUserEmail(String userEmail);

	/**
	 * Returns the otp of this signup otp.
	 *
	 * @return the otp of this signup otp
	 */
	@AutoEscape
	public String getOtp();

	/**
	 * Sets the otp of this signup otp.
	 *
	 * @param otp the otp of this signup otp
	 */
	public void setOtp(String otp);

	/**
	 * Returns the status of this signup otp.
	 *
	 * @return the status of this signup otp
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this signup otp is status.
	 *
	 * @return <code>true</code> if this signup otp is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this signup otp is status.
	 *
	 * @param status the status of this signup otp
	 */
	public void setStatus(boolean status);

	@Override
	public SignupOTP cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}