create table a_Case_management (
	uuid_ VARCHAR(75) null,
	caseId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	patientId LONG,
	doctorId LONG,
	doctorUserId LONG,
	caseTitle VARCHAR(75) null,
	notes VARCHAR(75) null,
	status VARCHAR(75) null,
	bloodPressure VARCHAR(75) null,
	height DOUBLE,
	weight DOUBLE,
	diagnosis VARCHAR(75) null,
	treatment VARCHAR(75) null,
	consultationFee DOUBLE,
	medicineCharges DOUBLE,
	testCharges DOUBLE,
	totalAmount DOUBLE,
	paymentStatus VARCHAR(75) null
);