/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Doctor_MgmtDB.model.impl;

import Doctor_MgmtDB.model.DoctorProfile;

import Doctor_MgmtDB.service.DoctorProfileLocalServiceUtil;

/**
 * The extended model base implementation for the DoctorProfile service. Represents a row in the &quot;a_DoctorProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DoctorProfileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DoctorProfileImpl
 * @see DoctorProfile
 * @generated
 */
public abstract class DoctorProfileBaseImpl
	extends DoctorProfileModelImpl implements DoctorProfile {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a doctor profile model instance should use the <code>DoctorProfile</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DoctorProfileLocalServiceUtil.addDoctorProfile(this);
		}
		else {
			DoctorProfileLocalServiceUtil.updateDoctorProfile(this);
		}
	}

}