/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Appointment_SchedulingDB.model.impl;

import Appointment_SchedulingDB.model.appointmentTable;

import Appointment_SchedulingDB.service.appointmentTableLocalServiceUtil;

/**
 * The extended model base implementation for the appointmentTable service. Represents a row in the &quot;AS_appointmentTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link appointmentTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see appointmentTableImpl
 * @see appointmentTable
 * @generated
 */
public abstract class appointmentTableBaseImpl
	extends appointmentTableModelImpl implements appointmentTable {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appointment table model instance should use the <code>appointmentTable</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			appointmentTableLocalServiceUtil.addappointmentTable(this);
		}
		else {
			appointmentTableLocalServiceUtil.updateappointmentTable(this);
		}
	}

}