/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Appointment_SchedulingDB.model.impl;

import Appointment_SchedulingDB.model.appointmentTable;
import Appointment_SchedulingDB.model.appointmentTableModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the appointmentTable service. Represents a row in the &quot;AS_appointmentTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>appointmentTableModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link appointmentTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see appointmentTableImpl
 * @generated
 */
@JSON(strict = true)
public class appointmentTableModelImpl
	extends BaseModelImpl<appointmentTable> implements appointmentTableModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appointment table model instance should use the <code>appointmentTable</code> interface instead.
	 */
	public static final String TABLE_NAME = "AS_appointmentTable";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"appointmentId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"doctorId", Types.BIGINT}, {"patientId", Types.BIGINT},
		{"appointmentDate", Types.TIMESTAMP}, {"timeSlot", Types.VARCHAR},
		{"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appointmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("doctorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("patientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appointmentDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("timeSlot", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AS_appointmentTable (uuid_ VARCHAR(75) null,appointmentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,doctorId LONG,patientId LONG,appointmentDate DATE null,timeSlot VARCHAR(75) null,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table AS_appointmentTable";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appointmentTable.appointmentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AS_appointmentTable.appointmentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOCTORID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PATIENTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPOINTMENTID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public appointmentTableModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appointmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppointmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appointmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return appointmentTable.class;
	}

	@Override
	public String getModelClassName() {
		return appointmentTable.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<appointmentTable, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<appointmentTable, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<appointmentTable, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((appointmentTable)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<appointmentTable, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<appointmentTable, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(appointmentTable)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<appointmentTable, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<appointmentTable, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<appointmentTable, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<appointmentTable, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<appointmentTable, Object>>();

			attributeGetterFunctions.put("uuid", appointmentTable::getUuid);
			attributeGetterFunctions.put(
				"appointmentId", appointmentTable::getAppointmentId);
			attributeGetterFunctions.put(
				"groupId", appointmentTable::getGroupId);
			attributeGetterFunctions.put(
				"companyId", appointmentTable::getCompanyId);
			attributeGetterFunctions.put("userId", appointmentTable::getUserId);
			attributeGetterFunctions.put(
				"userName", appointmentTable::getUserName);
			attributeGetterFunctions.put(
				"createDate", appointmentTable::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", appointmentTable::getModifiedDate);
			attributeGetterFunctions.put(
				"doctorId", appointmentTable::getDoctorId);
			attributeGetterFunctions.put(
				"patientId", appointmentTable::getPatientId);
			attributeGetterFunctions.put(
				"appointmentDate", appointmentTable::getAppointmentDate);
			attributeGetterFunctions.put(
				"timeSlot", appointmentTable::getTimeSlot);
			attributeGetterFunctions.put("status", appointmentTable::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<appointmentTable, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<appointmentTable, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<appointmentTable, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<appointmentTable, String>)
					appointmentTable::setUuid);
			attributeSetterBiConsumers.put(
				"appointmentId",
				(BiConsumer<appointmentTable, Long>)
					appointmentTable::setAppointmentId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<appointmentTable, Long>)
					appointmentTable::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<appointmentTable, Long>)
					appointmentTable::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<appointmentTable, Long>)
					appointmentTable::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<appointmentTable, String>)
					appointmentTable::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<appointmentTable, Date>)
					appointmentTable::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<appointmentTable, Date>)
					appointmentTable::setModifiedDate);
			attributeSetterBiConsumers.put(
				"doctorId",
				(BiConsumer<appointmentTable, Long>)
					appointmentTable::setDoctorId);
			attributeSetterBiConsumers.put(
				"patientId",
				(BiConsumer<appointmentTable, Long>)
					appointmentTable::setPatientId);
			attributeSetterBiConsumers.put(
				"appointmentDate",
				(BiConsumer<appointmentTable, Date>)
					appointmentTable::setAppointmentDate);
			attributeSetterBiConsumers.put(
				"timeSlot",
				(BiConsumer<appointmentTable, String>)
					appointmentTable::setTimeSlot);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<appointmentTable, String>)
					appointmentTable::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAppointmentId() {
		return _appointmentId;
	}

	@Override
	public void setAppointmentId(long appointmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appointmentId = appointmentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getDoctorId() {
		return _doctorId;
	}

	@Override
	public void setDoctorId(long doctorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_doctorId = doctorId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDoctorId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("doctorId"));
	}

	@JSON
	@Override
	public long getPatientId() {
		return _patientId;
	}

	@Override
	public void setPatientId(long patientId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_patientId = patientId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPatientId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("patientId"));
	}

	@JSON
	@Override
	public Date getAppointmentDate() {
		return _appointmentDate;
	}

	@Override
	public void setAppointmentDate(Date appointmentDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appointmentDate = appointmentDate;
	}

	@JSON
	@Override
	public String getTimeSlot() {
		if (_timeSlot == null) {
			return "";
		}
		else {
			return _timeSlot;
		}
	}

	@Override
	public void setTimeSlot(String timeSlot) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timeSlot = timeSlot;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(appointmentTable.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), appointmentTable.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public appointmentTable toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, appointmentTable>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		appointmentTableImpl appointmentTableImpl = new appointmentTableImpl();

		appointmentTableImpl.setUuid(getUuid());
		appointmentTableImpl.setAppointmentId(getAppointmentId());
		appointmentTableImpl.setGroupId(getGroupId());
		appointmentTableImpl.setCompanyId(getCompanyId());
		appointmentTableImpl.setUserId(getUserId());
		appointmentTableImpl.setUserName(getUserName());
		appointmentTableImpl.setCreateDate(getCreateDate());
		appointmentTableImpl.setModifiedDate(getModifiedDate());
		appointmentTableImpl.setDoctorId(getDoctorId());
		appointmentTableImpl.setPatientId(getPatientId());
		appointmentTableImpl.setAppointmentDate(getAppointmentDate());
		appointmentTableImpl.setTimeSlot(getTimeSlot());
		appointmentTableImpl.setStatus(getStatus());

		appointmentTableImpl.resetOriginalValues();

		return appointmentTableImpl;
	}

	@Override
	public appointmentTable cloneWithOriginalValues() {
		appointmentTableImpl appointmentTableImpl = new appointmentTableImpl();

		appointmentTableImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		appointmentTableImpl.setAppointmentId(
			this.<Long>getColumnOriginalValue("appointmentId"));
		appointmentTableImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appointmentTableImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appointmentTableImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		appointmentTableImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		appointmentTableImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appointmentTableImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appointmentTableImpl.setDoctorId(
			this.<Long>getColumnOriginalValue("doctorId"));
		appointmentTableImpl.setPatientId(
			this.<Long>getColumnOriginalValue("patientId"));
		appointmentTableImpl.setAppointmentDate(
			this.<Date>getColumnOriginalValue("appointmentDate"));
		appointmentTableImpl.setTimeSlot(
			this.<String>getColumnOriginalValue("timeSlot"));
		appointmentTableImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));

		return appointmentTableImpl;
	}

	@Override
	public int compareTo(appointmentTable appointmentTable) {
		long primaryKey = appointmentTable.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof appointmentTable)) {
			return false;
		}

		appointmentTable appointmentTable = (appointmentTable)object;

		long primaryKey = appointmentTable.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<appointmentTable> toCacheModel() {
		appointmentTableCacheModel appointmentTableCacheModel =
			new appointmentTableCacheModel();

		appointmentTableCacheModel.uuid = getUuid();

		String uuid = appointmentTableCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appointmentTableCacheModel.uuid = null;
		}

		appointmentTableCacheModel.appointmentId = getAppointmentId();

		appointmentTableCacheModel.groupId = getGroupId();

		appointmentTableCacheModel.companyId = getCompanyId();

		appointmentTableCacheModel.userId = getUserId();

		appointmentTableCacheModel.userName = getUserName();

		String userName = appointmentTableCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			appointmentTableCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			appointmentTableCacheModel.createDate = createDate.getTime();
		}
		else {
			appointmentTableCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appointmentTableCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appointmentTableCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appointmentTableCacheModel.doctorId = getDoctorId();

		appointmentTableCacheModel.patientId = getPatientId();

		Date appointmentDate = getAppointmentDate();

		if (appointmentDate != null) {
			appointmentTableCacheModel.appointmentDate =
				appointmentDate.getTime();
		}
		else {
			appointmentTableCacheModel.appointmentDate = Long.MIN_VALUE;
		}

		appointmentTableCacheModel.timeSlot = getTimeSlot();

		String timeSlot = appointmentTableCacheModel.timeSlot;

		if ((timeSlot != null) && (timeSlot.length() == 0)) {
			appointmentTableCacheModel.timeSlot = null;
		}

		appointmentTableCacheModel.status = getStatus();

		String status = appointmentTableCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			appointmentTableCacheModel.status = null;
		}

		return appointmentTableCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<appointmentTable, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<appointmentTable, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<appointmentTable, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(appointmentTable)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, appointmentTable>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					appointmentTable.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _appointmentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _doctorId;
	private long _patientId;
	private Date _appointmentDate;
	private String _timeSlot;
	private String _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<appointmentTable, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((appointmentTable)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("appointmentId", _appointmentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("doctorId", _doctorId);
		_columnOriginalValues.put("patientId", _patientId);
		_columnOriginalValues.put("appointmentDate", _appointmentDate);
		_columnOriginalValues.put("timeSlot", _timeSlot);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("appointmentId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("doctorId", 256L);

		columnBitmasks.put("patientId", 512L);

		columnBitmasks.put("appointmentDate", 1024L);

		columnBitmasks.put("timeSlot", 2048L);

		columnBitmasks.put("status", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private appointmentTable _escapedModel;

}