/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ClgDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Clg_Table service. Represents a row in the &quot;B_Clg_Table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ClgDB.model.impl.Clg_TableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ClgDB.model.impl.Clg_TableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Clg_Table
 * @generated
 */
@ProviderType
public interface Clg_TableModel
	extends BaseModel<Clg_Table>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a clg_ table model instance should use the {@link Clg_Table} interface instead.
	 */

	/**
	 * Returns the primary key of this clg_ table.
	 *
	 * @return the primary key of this clg_ table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this clg_ table.
	 *
	 * @param primaryKey the primary key of this clg_ table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this clg_ table.
	 *
	 * @return the uuid of this clg_ table
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this clg_ table.
	 *
	 * @param uuid the uuid of this clg_ table
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the clg ID of this clg_ table.
	 *
	 * @return the clg ID of this clg_ table
	 */
	public long getClgId();

	/**
	 * Sets the clg ID of this clg_ table.
	 *
	 * @param ClgId the clg ID of this clg_ table
	 */
	public void setClgId(long ClgId);

	/**
	 * Returns the group ID of this clg_ table.
	 *
	 * @return the group ID of this clg_ table
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this clg_ table.
	 *
	 * @param groupId the group ID of this clg_ table
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this clg_ table.
	 *
	 * @return the company ID of this clg_ table
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this clg_ table.
	 *
	 * @param companyId the company ID of this clg_ table
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this clg_ table.
	 *
	 * @return the user ID of this clg_ table
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this clg_ table.
	 *
	 * @param userId the user ID of this clg_ table
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this clg_ table.
	 *
	 * @return the user uuid of this clg_ table
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this clg_ table.
	 *
	 * @param userUuid the user uuid of this clg_ table
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this clg_ table.
	 *
	 * @return the user name of this clg_ table
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this clg_ table.
	 *
	 * @param userName the user name of this clg_ table
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this clg_ table.
	 *
	 * @return the create date of this clg_ table
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this clg_ table.
	 *
	 * @param createDate the create date of this clg_ table
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this clg_ table.
	 *
	 * @return the modified date of this clg_ table
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this clg_ table.
	 *
	 * @param modifiedDate the modified date of this clg_ table
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this clg_ table.
	 *
	 * @return the name of this clg_ table
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this clg_ table.
	 *
	 * @param name the name of this clg_ table
	 */
	public void setName(String name);

	/**
	 * Returns the address of this clg_ table.
	 *
	 * @return the address of this clg_ table
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this clg_ table.
	 *
	 * @param address the address of this clg_ table
	 */
	public void setAddress(String address);

	/**
	 * Returns the age of this clg_ table.
	 *
	 * @return the age of this clg_ table
	 */
	public int getAge();

	/**
	 * Sets the age of this clg_ table.
	 *
	 * @param age the age of this clg_ table
	 */
	public void setAge(int age);

	/**
	 * Returns the dob of this clg_ table.
	 *
	 * @return the dob of this clg_ table
	 */
	public Date getDob();

	/**
	 * Sets the dob of this clg_ table.
	 *
	 * @param dob the dob of this clg_ table
	 */
	public void setDob(Date dob);

	@Override
	public Clg_Table cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}