/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package PatientRegistryDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PatientRegistry service. Represents a row in the &quot;a_PatientRegistry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>PatientRegistryDB.model.impl.PatientRegistryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>PatientRegistryDB.model.impl.PatientRegistryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PatientRegistry
 * @generated
 */
@ProviderType
public interface PatientRegistryModel
	extends BaseModel<PatientRegistry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patient registry model instance should use the {@link PatientRegistry} interface instead.
	 */

	/**
	 * Returns the primary key of this patient registry.
	 *
	 * @return the primary key of this patient registry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patient registry.
	 *
	 * @param primaryKey the primary key of this patient registry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this patient registry.
	 *
	 * @return the uuid of this patient registry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this patient registry.
	 *
	 * @param uuid the uuid of this patient registry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the patient ID of this patient registry.
	 *
	 * @return the patient ID of this patient registry
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this patient registry.
	 *
	 * @param patientId the patient ID of this patient registry
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the group ID of this patient registry.
	 *
	 * @return the group ID of this patient registry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this patient registry.
	 *
	 * @param groupId the group ID of this patient registry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this patient registry.
	 *
	 * @return the company ID of this patient registry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this patient registry.
	 *
	 * @param companyId the company ID of this patient registry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this patient registry.
	 *
	 * @return the user ID of this patient registry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this patient registry.
	 *
	 * @param userId the user ID of this patient registry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this patient registry.
	 *
	 * @return the user uuid of this patient registry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this patient registry.
	 *
	 * @param userUuid the user uuid of this patient registry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this patient registry.
	 *
	 * @return the user name of this patient registry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this patient registry.
	 *
	 * @param userName the user name of this patient registry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this patient registry.
	 *
	 * @return the create date of this patient registry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this patient registry.
	 *
	 * @param createDate the create date of this patient registry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this patient registry.
	 *
	 * @return the modified date of this patient registry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this patient registry.
	 *
	 * @param modifiedDate the modified date of this patient registry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this patient registry.
	 *
	 * @return the first name of this patient registry
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this patient registry.
	 *
	 * @param firstName the first name of this patient registry
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this patient registry.
	 *
	 * @return the last name of this patient registry
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this patient registry.
	 *
	 * @param lastName the last name of this patient registry
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the date of birth of this patient registry.
	 *
	 * @return the date of birth of this patient registry
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this patient registry.
	 *
	 * @param dateOfBirth the date of birth of this patient registry
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the gender of this patient registry.
	 *
	 * @return the gender of this patient registry
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this patient registry.
	 *
	 * @param gender the gender of this patient registry
	 */
	public void setGender(String gender);

	/**
	 * Returns the contact number of this patient registry.
	 *
	 * @return the contact number of this patient registry
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this patient registry.
	 *
	 * @param contactNumber the contact number of this patient registry
	 */
	public void setContactNumber(String contactNumber);

	/**
	 * Returns the email of this patient registry.
	 *
	 * @return the email of this patient registry
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this patient registry.
	 *
	 * @param email the email of this patient registry
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this patient registry.
	 *
	 * @return the address of this patient registry
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this patient registry.
	 *
	 * @param address the address of this patient registry
	 */
	public void setAddress(String address);

	/**
	 * Returns the city of this patient registry.
	 *
	 * @return the city of this patient registry
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this patient registry.
	 *
	 * @param city the city of this patient registry
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this patient registry.
	 *
	 * @return the state of this patient registry
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this patient registry.
	 *
	 * @param state the state of this patient registry
	 */
	public void setState(String state);

	/**
	 * Returns the pincode of this patient registry.
	 *
	 * @return the pincode of this patient registry
	 */
	@AutoEscape
	public String getPincode();

	/**
	 * Sets the pincode of this patient registry.
	 *
	 * @param pincode the pincode of this patient registry
	 */
	public void setPincode(String pincode);

	/**
	 * Returns the emergency contact name of this patient registry.
	 *
	 * @return the emergency contact name of this patient registry
	 */
	@AutoEscape
	public String getEmergencyContactName();

	/**
	 * Sets the emergency contact name of this patient registry.
	 *
	 * @param emergencyContactName the emergency contact name of this patient registry
	 */
	public void setEmergencyContactName(String emergencyContactName);

	/**
	 * Returns the emergency contact number of this patient registry.
	 *
	 * @return the emergency contact number of this patient registry
	 */
	@AutoEscape
	public String getEmergencyContactNumber();

	/**
	 * Sets the emergency contact number of this patient registry.
	 *
	 * @param emergencyContactNumber the emergency contact number of this patient registry
	 */
	public void setEmergencyContactNumber(String emergencyContactNumber);

	/**
	 * Returns the blood group of this patient registry.
	 *
	 * @return the blood group of this patient registry
	 */
	@AutoEscape
	public String getBloodGroup();

	/**
	 * Sets the blood group of this patient registry.
	 *
	 * @param bloodGroup the blood group of this patient registry
	 */
	public void setBloodGroup(String bloodGroup);

	/**
	 * Returns the medical history of this patient registry.
	 *
	 * @return the medical history of this patient registry
	 */
	@AutoEscape
	public String getMedicalHistory();

	/**
	 * Sets the medical history of this patient registry.
	 *
	 * @param medicalHistory the medical history of this patient registry
	 */
	public void setMedicalHistory(String medicalHistory);

	/**
	 * Returns the allergies of this patient registry.
	 *
	 * @return the allergies of this patient registry
	 */
	@AutoEscape
	public String getAllergies();

	/**
	 * Sets the allergies of this patient registry.
	 *
	 * @param allergies the allergies of this patient registry
	 */
	public void setAllergies(String allergies);

	@Override
	public PatientRegistry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}