/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package PatientRegistryDB.model.impl;

import PatientRegistryDB.model.PatientRegistry;

import PatientRegistryDB.service.PatientRegistryLocalServiceUtil;

/**
 * The extended model base implementation for the PatientRegistry service. Represents a row in the &quot;a_PatientRegistry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatientRegistryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PatientRegistryImpl
 * @see PatientRegistry
 * @generated
 */
public abstract class PatientRegistryBaseImpl
	extends PatientRegistryModelImpl implements PatientRegistry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patient registry model instance should use the <code>PatientRegistry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PatientRegistryLocalServiceUtil.addPatientRegistry(this);
		}
		else {
			PatientRegistryLocalServiceUtil.updatePatientRegistry(this);
		}
	}

}