/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Case_ManagementDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Case_management service. Represents a row in the &quot;a_Case_management&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>Case_ManagementDB.model.impl.Case_managementModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>Case_ManagementDB.model.impl.Case_managementImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Case_management
 * @generated
 */
@ProviderType
public interface Case_managementModel
	extends BaseModel<Case_management>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a case_management model instance should use the {@link Case_management} interface instead.
	 */

	/**
	 * Returns the primary key of this case_management.
	 *
	 * @return the primary key of this case_management
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this case_management.
	 *
	 * @param primaryKey the primary key of this case_management
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this case_management.
	 *
	 * @return the uuid of this case_management
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this case_management.
	 *
	 * @param uuid the uuid of this case_management
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the case ID of this case_management.
	 *
	 * @return the case ID of this case_management
	 */
	public long getCaseId();

	/**
	 * Sets the case ID of this case_management.
	 *
	 * @param caseId the case ID of this case_management
	 */
	public void setCaseId(long caseId);

	/**
	 * Returns the group ID of this case_management.
	 *
	 * @return the group ID of this case_management
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this case_management.
	 *
	 * @param groupId the group ID of this case_management
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this case_management.
	 *
	 * @return the company ID of this case_management
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this case_management.
	 *
	 * @param companyId the company ID of this case_management
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this case_management.
	 *
	 * @return the user ID of this case_management
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this case_management.
	 *
	 * @param userId the user ID of this case_management
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this case_management.
	 *
	 * @return the user uuid of this case_management
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this case_management.
	 *
	 * @param userUuid the user uuid of this case_management
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this case_management.
	 *
	 * @return the user name of this case_management
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this case_management.
	 *
	 * @param userName the user name of this case_management
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this case_management.
	 *
	 * @return the create date of this case_management
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this case_management.
	 *
	 * @param createDate the create date of this case_management
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this case_management.
	 *
	 * @return the modified date of this case_management
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this case_management.
	 *
	 * @param modifiedDate the modified date of this case_management
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the patient ID of this case_management.
	 *
	 * @return the patient ID of this case_management
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this case_management.
	 *
	 * @param patientId the patient ID of this case_management
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the doctor ID of this case_management.
	 *
	 * @return the doctor ID of this case_management
	 */
	public long getDoctorId();

	/**
	 * Sets the doctor ID of this case_management.
	 *
	 * @param doctorId the doctor ID of this case_management
	 */
	public void setDoctorId(long doctorId);

	/**
	 * Returns the doctor user ID of this case_management.
	 *
	 * @return the doctor user ID of this case_management
	 */
	public long getDoctorUserId();

	/**
	 * Sets the doctor user ID of this case_management.
	 *
	 * @param doctorUserId the doctor user ID of this case_management
	 */
	public void setDoctorUserId(long doctorUserId);

	/**
	 * Returns the doctor user uuid of this case_management.
	 *
	 * @return the doctor user uuid of this case_management
	 */
	public String getDoctorUserUuid();

	/**
	 * Sets the doctor user uuid of this case_management.
	 *
	 * @param doctorUserUuid the doctor user uuid of this case_management
	 */
	public void setDoctorUserUuid(String doctorUserUuid);

	/**
	 * Returns the case title of this case_management.
	 *
	 * @return the case title of this case_management
	 */
	@AutoEscape
	public String getCaseTitle();

	/**
	 * Sets the case title of this case_management.
	 *
	 * @param caseTitle the case title of this case_management
	 */
	public void setCaseTitle(String caseTitle);

	/**
	 * Returns the notes of this case_management.
	 *
	 * @return the notes of this case_management
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this case_management.
	 *
	 * @param notes the notes of this case_management
	 */
	public void setNotes(String notes);

	/**
	 * Returns the status of this case_management.
	 *
	 * @return the status of this case_management
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this case_management.
	 *
	 * @param status the status of this case_management
	 */
	public void setStatus(String status);

	/**
	 * Returns the blood pressure of this case_management.
	 *
	 * @return the blood pressure of this case_management
	 */
	@AutoEscape
	public String getBloodPressure();

	/**
	 * Sets the blood pressure of this case_management.
	 *
	 * @param bloodPressure the blood pressure of this case_management
	 */
	public void setBloodPressure(String bloodPressure);

	/**
	 * Returns the height of this case_management.
	 *
	 * @return the height of this case_management
	 */
	public double getHeight();

	/**
	 * Sets the height of this case_management.
	 *
	 * @param height the height of this case_management
	 */
	public void setHeight(double height);

	/**
	 * Returns the weight of this case_management.
	 *
	 * @return the weight of this case_management
	 */
	public double getWeight();

	/**
	 * Sets the weight of this case_management.
	 *
	 * @param weight the weight of this case_management
	 */
	public void setWeight(double weight);

	/**
	 * Returns the diagnosis of this case_management.
	 *
	 * @return the diagnosis of this case_management
	 */
	@AutoEscape
	public String getDiagnosis();

	/**
	 * Sets the diagnosis of this case_management.
	 *
	 * @param diagnosis the diagnosis of this case_management
	 */
	public void setDiagnosis(String diagnosis);

	/**
	 * Returns the treatment of this case_management.
	 *
	 * @return the treatment of this case_management
	 */
	@AutoEscape
	public String getTreatment();

	/**
	 * Sets the treatment of this case_management.
	 *
	 * @param treatment the treatment of this case_management
	 */
	public void setTreatment(String treatment);

	/**
	 * Returns the consultation fee of this case_management.
	 *
	 * @return the consultation fee of this case_management
	 */
	public double getConsultationFee();

	/**
	 * Sets the consultation fee of this case_management.
	 *
	 * @param consultationFee the consultation fee of this case_management
	 */
	public void setConsultationFee(double consultationFee);

	/**
	 * Returns the medicine charges of this case_management.
	 *
	 * @return the medicine charges of this case_management
	 */
	public double getMedicineCharges();

	/**
	 * Sets the medicine charges of this case_management.
	 *
	 * @param medicineCharges the medicine charges of this case_management
	 */
	public void setMedicineCharges(double medicineCharges);

	/**
	 * Returns the test charges of this case_management.
	 *
	 * @return the test charges of this case_management
	 */
	public double getTestCharges();

	/**
	 * Sets the test charges of this case_management.
	 *
	 * @param testCharges the test charges of this case_management
	 */
	public void setTestCharges(double testCharges);

	/**
	 * Returns the total amount of this case_management.
	 *
	 * @return the total amount of this case_management
	 */
	public double getTotalAmount();

	/**
	 * Sets the total amount of this case_management.
	 *
	 * @param totalAmount the total amount of this case_management
	 */
	public void setTotalAmount(double totalAmount);

	/**
	 * Returns the payment status of this case_management.
	 *
	 * @return the payment status of this case_management
	 */
	@AutoEscape
	public String getPaymentStatus();

	/**
	 * Sets the payment status of this case_management.
	 *
	 * @param paymentStatus the payment status of this case_management
	 */
	public void setPaymentStatus(String paymentStatus);

	@Override
	public Case_management cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}