/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package BankDB.model.impl;

import BankDB.model.BankTable;

import BankDB.service.BankTableLocalServiceUtil;

/**
 * The extended model base implementation for the BankTable service. Represents a row in the &quot;B_BankTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BankTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BankTableImpl
 * @see BankTable
 * @generated
 */
public abstract class BankTableBaseImpl
	extends BankTableModelImpl implements BankTable {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bank table model instance should use the <code>BankTable</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BankTableLocalServiceUtil.addBankTable(this);
		}
		else {
			BankTableLocalServiceUtil.updateBankTable(this);
		}
	}

}