/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package BankDB.model.impl;

import BankDB.model.BankTable;
import BankDB.model.BankTableModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BankTable service. Represents a row in the &quot;B_BankTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BankTableModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BankTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BankTableImpl
 * @generated
 */
@JSON(strict = true)
public class BankTableModelImpl
	extends BaseModelImpl<BankTable> implements BankTableModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bank table model instance should use the <code>BankTable</code> interface instead.
	 */
	public static final String TABLE_NAME = "B_BankTable";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"BId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"Account_Number", Types.BIGINT}, {"Account_Type", Types.VARCHAR},
		{"IFSC_Code", Types.VARCHAR}, {"Account_Status", Types.VARCHAR},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("BId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Account_Number", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Account_Type", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("IFSC_Code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Account_Status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table B_BankTable (uuid_ VARCHAR(75) null,BId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,Account_Number LONG,Account_Type VARCHAR(75) null,IFSC_Code VARCHAR(75) null,Account_Status VARCHAR(75) null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table B_BankTable";

	public static final String ORDER_BY_JPQL =
		" ORDER BY bankTable.Account_Number ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY B_BankTable.Account_Number ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCOUNT_TYPE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCOUNT_NUMBER_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BankTableModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _BId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _BId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BankTable.class;
	}

	@Override
	public String getModelClassName() {
		return BankTable.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BankTable, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BankTable, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BankTable, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((BankTable)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BankTable, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BankTable, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BankTable)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BankTable, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BankTable, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BankTable, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BankTable, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<BankTable, Object>>();

			attributeGetterFunctions.put("uuid", BankTable::getUuid);
			attributeGetterFunctions.put("BId", BankTable::getBId);
			attributeGetterFunctions.put("groupId", BankTable::getGroupId);
			attributeGetterFunctions.put("companyId", BankTable::getCompanyId);
			attributeGetterFunctions.put("userId", BankTable::getUserId);
			attributeGetterFunctions.put("userName", BankTable::getUserName);
			attributeGetterFunctions.put(
				"createDate", BankTable::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", BankTable::getModifiedDate);
			attributeGetterFunctions.put(
				"Account_Number", BankTable::getAccount_Number);
			attributeGetterFunctions.put(
				"Account_Type", BankTable::getAccount_Type);
			attributeGetterFunctions.put("IFSC_Code", BankTable::getIFSC_Code);
			attributeGetterFunctions.put(
				"Account_Status", BankTable::getAccount_Status);
			attributeGetterFunctions.put("status", BankTable::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<BankTable, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BankTable, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<BankTable, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<BankTable, String>)BankTable::setUuid);
			attributeSetterBiConsumers.put(
				"BId", (BiConsumer<BankTable, Long>)BankTable::setBId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<BankTable, Long>)BankTable::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<BankTable, Long>)BankTable::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<BankTable, Long>)BankTable::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<BankTable, String>)BankTable::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<BankTable, Date>)BankTable::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<BankTable, Date>)BankTable::setModifiedDate);
			attributeSetterBiConsumers.put(
				"Account_Number",
				(BiConsumer<BankTable, Long>)BankTable::setAccount_Number);
			attributeSetterBiConsumers.put(
				"Account_Type",
				(BiConsumer<BankTable, String>)BankTable::setAccount_Type);
			attributeSetterBiConsumers.put(
				"IFSC_Code",
				(BiConsumer<BankTable, String>)BankTable::setIFSC_Code);
			attributeSetterBiConsumers.put(
				"Account_Status",
				(BiConsumer<BankTable, String>)BankTable::setAccount_Status);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<BankTable, Integer>)BankTable::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getBId() {
		return _BId;
	}

	@Override
	public void setBId(long BId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_BId = BId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAccount_Number() {
		return _Account_Number;
	}

	@Override
	public void setAccount_Number(long Account_Number) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Account_Number = Account_Number;
	}

	@JSON
	@Override
	public String getAccount_Type() {
		if (_Account_Type == null) {
			return "";
		}
		else {
			return _Account_Type;
		}
	}

	@Override
	public void setAccount_Type(String Account_Type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Account_Type = Account_Type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAccount_Type() {
		return getColumnOriginalValue("Account_Type");
	}

	@JSON
	@Override
	public String getIFSC_Code() {
		if (_IFSC_Code == null) {
			return "";
		}
		else {
			return _IFSC_Code;
		}
	}

	@Override
	public void setIFSC_Code(String IFSC_Code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_IFSC_Code = IFSC_Code;
	}

	@JSON
	@Override
	public String getAccount_Status() {
		if (_Account_Status == null) {
			return "";
		}
		else {
			return _Account_Status;
		}
	}

	@Override
	public void setAccount_Status(String Account_Status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Account_Status = Account_Status;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(BankTable.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BankTable.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BankTable toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BankTable>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BankTableImpl bankTableImpl = new BankTableImpl();

		bankTableImpl.setUuid(getUuid());
		bankTableImpl.setBId(getBId());
		bankTableImpl.setGroupId(getGroupId());
		bankTableImpl.setCompanyId(getCompanyId());
		bankTableImpl.setUserId(getUserId());
		bankTableImpl.setUserName(getUserName());
		bankTableImpl.setCreateDate(getCreateDate());
		bankTableImpl.setModifiedDate(getModifiedDate());
		bankTableImpl.setAccount_Number(getAccount_Number());
		bankTableImpl.setAccount_Type(getAccount_Type());
		bankTableImpl.setIFSC_Code(getIFSC_Code());
		bankTableImpl.setAccount_Status(getAccount_Status());
		bankTableImpl.setStatus(getStatus());

		bankTableImpl.resetOriginalValues();

		return bankTableImpl;
	}

	@Override
	public BankTable cloneWithOriginalValues() {
		BankTableImpl bankTableImpl = new BankTableImpl();

		bankTableImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		bankTableImpl.setBId(this.<Long>getColumnOriginalValue("BId"));
		bankTableImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		bankTableImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		bankTableImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		bankTableImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		bankTableImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		bankTableImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		bankTableImpl.setAccount_Number(
			this.<Long>getColumnOriginalValue("Account_Number"));
		bankTableImpl.setAccount_Type(
			this.<String>getColumnOriginalValue("Account_Type"));
		bankTableImpl.setIFSC_Code(
			this.<String>getColumnOriginalValue("IFSC_Code"));
		bankTableImpl.setAccount_Status(
			this.<String>getColumnOriginalValue("Account_Status"));
		bankTableImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));

		return bankTableImpl;
	}

	@Override
	public int compareTo(BankTable bankTable) {
		int value = 0;

		if (getAccount_Number() < bankTable.getAccount_Number()) {
			value = -1;
		}
		else if (getAccount_Number() > bankTable.getAccount_Number()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BankTable)) {
			return false;
		}

		BankTable bankTable = (BankTable)object;

		long primaryKey = bankTable.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BankTable> toCacheModel() {
		BankTableCacheModel bankTableCacheModel = new BankTableCacheModel();

		bankTableCacheModel.uuid = getUuid();

		String uuid = bankTableCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			bankTableCacheModel.uuid = null;
		}

		bankTableCacheModel.BId = getBId();

		bankTableCacheModel.groupId = getGroupId();

		bankTableCacheModel.companyId = getCompanyId();

		bankTableCacheModel.userId = getUserId();

		bankTableCacheModel.userName = getUserName();

		String userName = bankTableCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			bankTableCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			bankTableCacheModel.createDate = createDate.getTime();
		}
		else {
			bankTableCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			bankTableCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			bankTableCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		bankTableCacheModel.Account_Number = getAccount_Number();

		bankTableCacheModel.Account_Type = getAccount_Type();

		String Account_Type = bankTableCacheModel.Account_Type;

		if ((Account_Type != null) && (Account_Type.length() == 0)) {
			bankTableCacheModel.Account_Type = null;
		}

		bankTableCacheModel.IFSC_Code = getIFSC_Code();

		String IFSC_Code = bankTableCacheModel.IFSC_Code;

		if ((IFSC_Code != null) && (IFSC_Code.length() == 0)) {
			bankTableCacheModel.IFSC_Code = null;
		}

		bankTableCacheModel.Account_Status = getAccount_Status();

		String Account_Status = bankTableCacheModel.Account_Status;

		if ((Account_Status != null) && (Account_Status.length() == 0)) {
			bankTableCacheModel.Account_Status = null;
		}

		bankTableCacheModel.status = getStatus();

		return bankTableCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BankTable, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BankTable, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BankTable, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BankTable)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BankTable>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BankTable.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _BId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _Account_Number;
	private String _Account_Type;
	private String _IFSC_Code;
	private String _Account_Status;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BankTable, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BankTable)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("BId", _BId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("Account_Number", _Account_Number);
		_columnOriginalValues.put("Account_Type", _Account_Type);
		_columnOriginalValues.put("IFSC_Code", _IFSC_Code);
		_columnOriginalValues.put("Account_Status", _Account_Status);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("BId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("Account_Number", 256L);

		columnBitmasks.put("Account_Type", 512L);

		columnBitmasks.put("IFSC_Code", 1024L);

		columnBitmasks.put("Account_Status", 2048L);

		columnBitmasks.put("status", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BankTable _escapedModel;

}