/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package LoanDB.model.impl;

import LoanDB.model.Loan;

import LoanDB.service.LoanLocalServiceUtil;

/**
 * The extended model base implementation for the Loan service. Represents a row in the &quot;ATS_Loan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoanImpl
 * @see Loan
 * @generated
 */
public abstract class LoanBaseImpl extends LoanModelImpl implements Loan {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loan model instance should use the <code>Loan</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LoanLocalServiceUtil.addLoan(this);
		}
		else {
			LoanLocalServiceUtil.updateLoan(this);
		}
	}

}