/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package LoanDB.model.impl;

import LoanDB.model.Loan;
import LoanDB.model.LoanModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Loan service. Represents a row in the &quot;ATS_Loan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LoanModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoanImpl
 * @generated
 */
public class LoanModelImpl extends BaseModelImpl<Loan> implements LoanModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loan model instance should use the <code>Loan</code> interface instead.
	 */
	public static final String TABLE_NAME = "ATS_Loan";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"loanId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"customerId", Types.BIGINT}, {"amount", Types.DOUBLE},
		{"interestRate", Types.DOUBLE}, {"loanType", Types.VARCHAR},
		{"tenureMonths", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loanId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("customerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("amount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("interestRate", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("loanType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tenureMonths", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ATS_Loan (uuid_ VARCHAR(75) null,loanId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,customerId LONG,amount DOUBLE,interestRate DOUBLE,loanType VARCHAR(75) null,tenureMonths INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table ATS_Loan";

	public static final String ORDER_BY_JPQL = " ORDER BY loan.loanId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY ATS_Loan.loanId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOANID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LoanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loanId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoanId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loanId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Loan.class;
	}

	@Override
	public String getModelClassName() {
		return Loan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Loan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Loan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Loan, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Loan)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Loan, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Loan, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Loan)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Loan, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Loan, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Loan, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Loan, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Loan, Object>>();

			attributeGetterFunctions.put("uuid", Loan::getUuid);
			attributeGetterFunctions.put("loanId", Loan::getLoanId);
			attributeGetterFunctions.put("groupId", Loan::getGroupId);
			attributeGetterFunctions.put("companyId", Loan::getCompanyId);
			attributeGetterFunctions.put("userId", Loan::getUserId);
			attributeGetterFunctions.put("userName", Loan::getUserName);
			attributeGetterFunctions.put("createDate", Loan::getCreateDate);
			attributeGetterFunctions.put("modifiedDate", Loan::getModifiedDate);
			attributeGetterFunctions.put("customerId", Loan::getCustomerId);
			attributeGetterFunctions.put("amount", Loan::getAmount);
			attributeGetterFunctions.put("interestRate", Loan::getInterestRate);
			attributeGetterFunctions.put("loanType", Loan::getLoanType);
			attributeGetterFunctions.put("tenureMonths", Loan::getTenureMonths);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Loan, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Loan, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Loan, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Loan, String>)Loan::setUuid);
			attributeSetterBiConsumers.put(
				"loanId", (BiConsumer<Loan, Long>)Loan::setLoanId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Loan, Long>)Loan::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Loan, Long>)Loan::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Loan, Long>)Loan::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Loan, String>)Loan::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Loan, Date>)Loan::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate", (BiConsumer<Loan, Date>)Loan::setModifiedDate);
			attributeSetterBiConsumers.put(
				"customerId", (BiConsumer<Loan, Long>)Loan::setCustomerId);
			attributeSetterBiConsumers.put(
				"amount", (BiConsumer<Loan, Double>)Loan::setAmount);
			attributeSetterBiConsumers.put(
				"interestRate",
				(BiConsumer<Loan, Double>)Loan::setInterestRate);
			attributeSetterBiConsumers.put(
				"loanType", (BiConsumer<Loan, String>)Loan::setLoanType);
			attributeSetterBiConsumers.put(
				"tenureMonths",
				(BiConsumer<Loan, Integer>)Loan::setTenureMonths);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getLoanId() {
		return _loanId;
	}

	@Override
	public void setLoanId(long loanId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_loanId = loanId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCustomerId() {
		return _customerId;
	}

	@Override
	public void setCustomerId(long customerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customerId = customerId;
	}

	@Override
	public double getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(double amount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amount = amount;
	}

	@Override
	public double getInterestRate() {
		return _interestRate;
	}

	@Override
	public void setInterestRate(double interestRate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_interestRate = interestRate;
	}

	@Override
	public String getLoanType() {
		if (_loanType == null) {
			return "";
		}
		else {
			return _loanType;
		}
	}

	@Override
	public void setLoanType(String loanType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_loanType = loanType;
	}

	@Override
	public int getTenureMonths() {
		return _tenureMonths;
	}

	@Override
	public void setTenureMonths(int tenureMonths) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tenureMonths = tenureMonths;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Loan.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Loan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Loan toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Loan>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoanImpl loanImpl = new LoanImpl();

		loanImpl.setUuid(getUuid());
		loanImpl.setLoanId(getLoanId());
		loanImpl.setGroupId(getGroupId());
		loanImpl.setCompanyId(getCompanyId());
		loanImpl.setUserId(getUserId());
		loanImpl.setUserName(getUserName());
		loanImpl.setCreateDate(getCreateDate());
		loanImpl.setModifiedDate(getModifiedDate());
		loanImpl.setCustomerId(getCustomerId());
		loanImpl.setAmount(getAmount());
		loanImpl.setInterestRate(getInterestRate());
		loanImpl.setLoanType(getLoanType());
		loanImpl.setTenureMonths(getTenureMonths());

		loanImpl.resetOriginalValues();

		return loanImpl;
	}

	@Override
	public Loan cloneWithOriginalValues() {
		LoanImpl loanImpl = new LoanImpl();

		loanImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		loanImpl.setLoanId(this.<Long>getColumnOriginalValue("loanId"));
		loanImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		loanImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		loanImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		loanImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		loanImpl.setCreateDate(this.<Date>getColumnOriginalValue("createDate"));
		loanImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		loanImpl.setCustomerId(this.<Long>getColumnOriginalValue("customerId"));
		loanImpl.setAmount(this.<Double>getColumnOriginalValue("amount"));
		loanImpl.setInterestRate(
			this.<Double>getColumnOriginalValue("interestRate"));
		loanImpl.setLoanType(this.<String>getColumnOriginalValue("loanType"));
		loanImpl.setTenureMonths(
			this.<Integer>getColumnOriginalValue("tenureMonths"));

		return loanImpl;
	}

	@Override
	public int compareTo(Loan loan) {
		long primaryKey = loan.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Loan)) {
			return false;
		}

		Loan loan = (Loan)object;

		long primaryKey = loan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Loan> toCacheModel() {
		LoanCacheModel loanCacheModel = new LoanCacheModel();

		loanCacheModel.uuid = getUuid();

		String uuid = loanCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			loanCacheModel.uuid = null;
		}

		loanCacheModel.loanId = getLoanId();

		loanCacheModel.groupId = getGroupId();

		loanCacheModel.companyId = getCompanyId();

		loanCacheModel.userId = getUserId();

		loanCacheModel.userName = getUserName();

		String userName = loanCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			loanCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			loanCacheModel.createDate = createDate.getTime();
		}
		else {
			loanCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			loanCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			loanCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		loanCacheModel.customerId = getCustomerId();

		loanCacheModel.amount = getAmount();

		loanCacheModel.interestRate = getInterestRate();

		loanCacheModel.loanType = getLoanType();

		String loanType = loanCacheModel.loanType;

		if ((loanType != null) && (loanType.length() == 0)) {
			loanCacheModel.loanType = null;
		}

		loanCacheModel.tenureMonths = getTenureMonths();

		return loanCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Loan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Loan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Loan, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Loan)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Loan>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Loan.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _loanId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _customerId;
	private double _amount;
	private double _interestRate;
	private String _loanType;
	private int _tenureMonths;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Loan, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Loan)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("loanId", _loanId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("customerId", _customerId);
		_columnOriginalValues.put("amount", _amount);
		_columnOriginalValues.put("interestRate", _interestRate);
		_columnOriginalValues.put("loanType", _loanType);
		_columnOriginalValues.put("tenureMonths", _tenureMonths);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("loanId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("customerId", 256L);

		columnBitmasks.put("amount", 512L);

		columnBitmasks.put("interestRate", 1024L);

		columnBitmasks.put("loanType", 2048L);

		columnBitmasks.put("tenureMonths", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Loan _escapedModel;

}