create table a_DoctorProfile (
	uuid_ VARCHAR(75) null,
	doctorId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	gender VARCHAR(75) null,
	dob DATE null,
	email VARCHAR(75) null,
	phone VARCHAR(75) null,
	imageId LONG,
	specialization VARCHAR(75) null,
	qualification VARCHAR(75) null,
	experienceYears INTEGER,
	languages VARCHAR(75) null,
	licenseNumber VARCHAR(75) null,
	availableDays VARCHAR(75) null,
	availableTime VARCHAR(75) null,
	hospitalLocation VARCHAR(75) null,
	consultationMode VARCHAR(75) null,
	address VARCHAR(75) null,
	bio VARCHAR(75) null,
	fees DOUBLE,
	rating DOUBLE
);