/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Appointment_SchedulingDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the appointmentTable service. Represents a row in the &quot;AS_appointmentTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>Appointment_SchedulingDB.model.impl.appointmentTableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>Appointment_SchedulingDB.model.impl.appointmentTableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see appointmentTable
 * @generated
 */
@ProviderType
public interface appointmentTableModel
	extends BaseModel<appointmentTable>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appointment table model instance should use the {@link appointmentTable} interface instead.
	 */

	/**
	 * Returns the primary key of this appointment table.
	 *
	 * @return the primary key of this appointment table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appointment table.
	 *
	 * @param primaryKey the primary key of this appointment table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this appointment table.
	 *
	 * @return the uuid of this appointment table
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this appointment table.
	 *
	 * @param uuid the uuid of this appointment table
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the appointment ID of this appointment table.
	 *
	 * @return the appointment ID of this appointment table
	 */
	public long getAppointmentId();

	/**
	 * Sets the appointment ID of this appointment table.
	 *
	 * @param appointmentId the appointment ID of this appointment table
	 */
	public void setAppointmentId(long appointmentId);

	/**
	 * Returns the group ID of this appointment table.
	 *
	 * @return the group ID of this appointment table
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this appointment table.
	 *
	 * @param groupId the group ID of this appointment table
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this appointment table.
	 *
	 * @return the company ID of this appointment table
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this appointment table.
	 *
	 * @param companyId the company ID of this appointment table
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this appointment table.
	 *
	 * @return the user ID of this appointment table
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this appointment table.
	 *
	 * @param userId the user ID of this appointment table
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this appointment table.
	 *
	 * @return the user uuid of this appointment table
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this appointment table.
	 *
	 * @param userUuid the user uuid of this appointment table
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this appointment table.
	 *
	 * @return the user name of this appointment table
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this appointment table.
	 *
	 * @param userName the user name of this appointment table
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this appointment table.
	 *
	 * @return the create date of this appointment table
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this appointment table.
	 *
	 * @param createDate the create date of this appointment table
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this appointment table.
	 *
	 * @return the modified date of this appointment table
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this appointment table.
	 *
	 * @param modifiedDate the modified date of this appointment table
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the doctor ID of this appointment table.
	 *
	 * @return the doctor ID of this appointment table
	 */
	public long getDoctorId();

	/**
	 * Sets the doctor ID of this appointment table.
	 *
	 * @param doctorId the doctor ID of this appointment table
	 */
	public void setDoctorId(long doctorId);

	/**
	 * Returns the patient ID of this appointment table.
	 *
	 * @return the patient ID of this appointment table
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this appointment table.
	 *
	 * @param patientId the patient ID of this appointment table
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the appointment date of this appointment table.
	 *
	 * @return the appointment date of this appointment table
	 */
	public Date getAppointmentDate();

	/**
	 * Sets the appointment date of this appointment table.
	 *
	 * @param appointmentDate the appointment date of this appointment table
	 */
	public void setAppointmentDate(Date appointmentDate);

	/**
	 * Returns the time slot of this appointment table.
	 *
	 * @return the time slot of this appointment table
	 */
	@AutoEscape
	public String getTimeSlot();

	/**
	 * Sets the time slot of this appointment table.
	 *
	 * @param timeSlot the time slot of this appointment table
	 */
	public void setTimeSlot(String timeSlot);

	/**
	 * Returns the status of this appointment table.
	 *
	 * @return the status of this appointment table
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this appointment table.
	 *
	 * @param status the status of this appointment table
	 */
	public void setStatus(String status);

	@Override
	public appointmentTable cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}