/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Case_ManagementDB.model.impl;

import Case_ManagementDB.model.Case_management;

import Case_ManagementDB.service.Case_managementLocalServiceUtil;

/**
 * The extended model base implementation for the Case_management service. Represents a row in the &quot;a_Case_management&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Case_managementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Case_managementImpl
 * @see Case_management
 * @generated
 */
public abstract class Case_managementBaseImpl
	extends Case_managementModelImpl implements Case_management {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a case_management model instance should use the <code>Case_management</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Case_managementLocalServiceUtil.addCase_management(this);
		}
		else {
			Case_managementLocalServiceUtil.updateCase_management(this);
		}
	}

}