/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package LoanDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CustomerTable service. Represents a row in the &quot;B_CustomerTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>LoanDB.model.impl.CustomerTableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>LoanDB.model.impl.CustomerTableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomerTable
 * @generated
 */
@ProviderType
public interface CustomerTableModel
	extends AuditedModel, BaseModel<CustomerTable>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer table model instance should use the {@link CustomerTable} interface instead.
	 */

	/**
	 * Returns the primary key of this customer table.
	 *
	 * @return the primary key of this customer table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer table.
	 *
	 * @param primaryKey the primary key of this customer table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the customer ID of this customer table.
	 *
	 * @return the customer ID of this customer table
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this customer table.
	 *
	 * @param customerId the customer ID of this customer table
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the name of this customer table.
	 *
	 * @return the name of this customer table
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this customer table.
	 *
	 * @param name the name of this customer table
	 */
	public void setName(String name);

	/**
	 * Returns the email of this customer table.
	 *
	 * @return the email of this customer table
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this customer table.
	 *
	 * @param email the email of this customer table
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this customer table.
	 *
	 * @return the phone of this customer table
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this customer table.
	 *
	 * @param phone the phone of this customer table
	 */
	public void setPhone(String phone);

	/**
	 * Returns the dob of this customer table.
	 *
	 * @return the dob of this customer table
	 */
	public Date getDob();

	/**
	 * Sets the dob of this customer table.
	 *
	 * @param dob the dob of this customer table
	 */
	public void setDob(Date dob);

	/**
	 * Returns the aadhar number of this customer table.
	 *
	 * @return the aadhar number of this customer table
	 */
	@AutoEscape
	public String getAadharNumber();

	/**
	 * Sets the aadhar number of this customer table.
	 *
	 * @param aadharNumber the aadhar number of this customer table
	 */
	public void setAadharNumber(String aadharNumber);

	/**
	 * Returns the pan number of this customer table.
	 *
	 * @return the pan number of this customer table
	 */
	@AutoEscape
	public String getPanNumber();

	/**
	 * Sets the pan number of this customer table.
	 *
	 * @param panNumber the pan number of this customer table
	 */
	public void setPanNumber(String panNumber);

	/**
	 * Returns the address of this customer table.
	 *
	 * @return the address of this customer table
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this customer table.
	 *
	 * @param address the address of this customer table
	 */
	public void setAddress(String address);

	/**
	 * Returns the company ID of this customer table.
	 *
	 * @return the company ID of this customer table
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this customer table.
	 *
	 * @param companyId the company ID of this customer table
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this customer table.
	 *
	 * @return the user ID of this customer table
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this customer table.
	 *
	 * @param userId the user ID of this customer table
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this customer table.
	 *
	 * @return the user uuid of this customer table
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this customer table.
	 *
	 * @param userUuid the user uuid of this customer table
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this customer table.
	 *
	 * @return the user name of this customer table
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this customer table.
	 *
	 * @param userName the user name of this customer table
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this customer table.
	 *
	 * @return the create date of this customer table
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this customer table.
	 *
	 * @param createDate the create date of this customer table
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this customer table.
	 *
	 * @return the modified date of this customer table
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this customer table.
	 *
	 * @param modifiedDate the modified date of this customer table
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public CustomerTable cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}