/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package LoanDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LoanTable service. Represents a row in the &quot;B_LoanTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>LoanDB.model.impl.LoanTableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>LoanDB.model.impl.LoanTableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoanTable
 * @generated
 */
@ProviderType
public interface LoanTableModel
	extends BaseModel<LoanTable>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loan table model instance should use the {@link LoanTable} interface instead.
	 */

	/**
	 * Returns the primary key of this loan table.
	 *
	 * @return the primary key of this loan table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loan table.
	 *
	 * @param primaryKey the primary key of this loan table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this loan table.
	 *
	 * @return the uuid of this loan table
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this loan table.
	 *
	 * @param uuid the uuid of this loan table
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the loan ID of this loan table.
	 *
	 * @return the loan ID of this loan table
	 */
	public long getLoanId();

	/**
	 * Sets the loan ID of this loan table.
	 *
	 * @param LoanId the loan ID of this loan table
	 */
	public void setLoanId(long LoanId);

	/**
	 * Returns the customer ID of this loan table.
	 *
	 * @return the customer ID of this loan table
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this loan table.
	 *
	 * @param customerId the customer ID of this loan table
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the loan type of this loan table.
	 *
	 * @return the loan type of this loan table
	 */
	@AutoEscape
	public String getLoanType();

	/**
	 * Sets the loan type of this loan table.
	 *
	 * @param loanType the loan type of this loan table
	 */
	public void setLoanType(String loanType);

	/**
	 * Returns the amount of this loan table.
	 *
	 * @return the amount of this loan table
	 */
	public double getAmount();

	/**
	 * Sets the amount of this loan table.
	 *
	 * @param amount the amount of this loan table
	 */
	public void setAmount(double amount);

	/**
	 * Returns the status of this loan table.
	 *
	 * @return the status of this loan table
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this loan table.
	 *
	 * @param status the status of this loan table
	 */
	public void setStatus(String status);

	/**
	 * Returns the application date of this loan table.
	 *
	 * @return the application date of this loan table
	 */
	public Date getApplicationDate();

	/**
	 * Sets the application date of this loan table.
	 *
	 * @param applicationDate the application date of this loan table
	 */
	public void setApplicationDate(Date applicationDate);

	/**
	 * Returns the interest rate of this loan table.
	 *
	 * @return the interest rate of this loan table
	 */
	public double getInterestRate();

	/**
	 * Sets the interest rate of this loan table.
	 *
	 * @param interestRate the interest rate of this loan table
	 */
	public void setInterestRate(double interestRate);

	/**
	 * Returns the tenure of this loan table.
	 *
	 * @return the tenure of this loan table
	 */
	public int getTenure();

	/**
	 * Sets the tenure of this loan table.
	 *
	 * @param tenure the tenure of this loan table
	 */
	public void setTenure(int tenure);

	/**
	 * Returns the remarks of this loan table.
	 *
	 * @return the remarks of this loan table
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this loan table.
	 *
	 * @param remarks the remarks of this loan table
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the company ID of this loan table.
	 *
	 * @return the company ID of this loan table
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loan table.
	 *
	 * @param companyId the company ID of this loan table
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this loan table.
	 *
	 * @return the user ID of this loan table
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loan table.
	 *
	 * @param userId the user ID of this loan table
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loan table.
	 *
	 * @return the user uuid of this loan table
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this loan table.
	 *
	 * @param userUuid the user uuid of this loan table
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loan table.
	 *
	 * @return the user name of this loan table
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loan table.
	 *
	 * @param userName the user name of this loan table
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loan table.
	 *
	 * @return the create date of this loan table
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loan table.
	 *
	 * @param createDate the create date of this loan table
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loan table.
	 *
	 * @return the modified date of this loan table
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loan table.
	 *
	 * @param modifiedDate the modified date of this loan table
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public LoanTable cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}