/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package otpDB.model.impl;

import otpDB.model.SignupOTP;

import otpDB.service.SignupOTPLocalServiceUtil;

/**
 * The extended model base implementation for the SignupOTP service. Represents a row in the &quot;a_SignupOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SignupOTPImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SignupOTPImpl
 * @see SignupOTP
 * @generated
 */
public abstract class SignupOTPBaseImpl
	extends SignupOTPModelImpl implements SignupOTP {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a signup otp model instance should use the <code>SignupOTP</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SignupOTPLocalServiceUtil.addSignupOTP(this);
		}
		else {
			SignupOTPLocalServiceUtil.updateSignupOTP(this);
		}
	}

}