/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package LoanDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Loan service. Represents a row in the &quot;ATS_Loan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>LoanDB.model.impl.LoanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>LoanDB.model.impl.LoanImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Loan
 * @generated
 */
@ProviderType
public interface LoanModel
	extends BaseModel<Loan>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loan model instance should use the {@link Loan} interface instead.
	 */

	/**
	 * Returns the primary key of this loan.
	 *
	 * @return the primary key of this loan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loan.
	 *
	 * @param primaryKey the primary key of this loan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this loan.
	 *
	 * @return the uuid of this loan
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this loan.
	 *
	 * @param uuid the uuid of this loan
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the loan ID of this loan.
	 *
	 * @return the loan ID of this loan
	 */
	public long getLoanId();

	/**
	 * Sets the loan ID of this loan.
	 *
	 * @param loanId the loan ID of this loan
	 */
	public void setLoanId(long loanId);

	/**
	 * Returns the group ID of this loan.
	 *
	 * @return the group ID of this loan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this loan.
	 *
	 * @param groupId the group ID of this loan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this loan.
	 *
	 * @return the company ID of this loan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loan.
	 *
	 * @param companyId the company ID of this loan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this loan.
	 *
	 * @return the user ID of this loan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loan.
	 *
	 * @param userId the user ID of this loan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loan.
	 *
	 * @return the user uuid of this loan
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this loan.
	 *
	 * @param userUuid the user uuid of this loan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loan.
	 *
	 * @return the user name of this loan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loan.
	 *
	 * @param userName the user name of this loan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loan.
	 *
	 * @return the create date of this loan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loan.
	 *
	 * @param createDate the create date of this loan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loan.
	 *
	 * @return the modified date of this loan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loan.
	 *
	 * @param modifiedDate the modified date of this loan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the customer ID of this loan.
	 *
	 * @return the customer ID of this loan
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this loan.
	 *
	 * @param customerId the customer ID of this loan
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the amount of this loan.
	 *
	 * @return the amount of this loan
	 */
	public double getAmount();

	/**
	 * Sets the amount of this loan.
	 *
	 * @param amount the amount of this loan
	 */
	public void setAmount(double amount);

	/**
	 * Returns the interest rate of this loan.
	 *
	 * @return the interest rate of this loan
	 */
	public double getInterestRate();

	/**
	 * Sets the interest rate of this loan.
	 *
	 * @param interestRate the interest rate of this loan
	 */
	public void setInterestRate(double interestRate);

	/**
	 * Returns the loan type of this loan.
	 *
	 * @return the loan type of this loan
	 */
	@AutoEscape
	public String getLoanType();

	/**
	 * Sets the loan type of this loan.
	 *
	 * @param loanType the loan type of this loan
	 */
	public void setLoanType(String loanType);

	/**
	 * Returns the tenure months of this loan.
	 *
	 * @return the tenure months of this loan
	 */
	public int getTenureMonths();

	/**
	 * Sets the tenure months of this loan.
	 *
	 * @param tenureMonths the tenure months of this loan
	 */
	public void setTenureMonths(int tenureMonths);

	@Override
	public Loan cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}