/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Appointment_SchedulingDB.service.base;

import Appointment_SchedulingDB.model.appointmentTable;

import Appointment_SchedulingDB.service.appointmentTableLocalService;
import Appointment_SchedulingDB.service.persistence.appointmentTablePersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the appointment table local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link Appointment_SchedulingDB.service.impl.appointmentTableLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Appointment_SchedulingDB.service.impl.appointmentTableLocalServiceImpl
 * @generated
 */
public abstract class appointmentTableLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, appointmentTableLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>appointmentTableLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>Appointment_SchedulingDB.service.appointmentTableLocalServiceUtil</code>.
	 */

	/**
	 * Adds the appointment table to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect appointmentTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param appointmentTable the appointment table
	 * @return the appointment table that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public appointmentTable addappointmentTable(
		appointmentTable appointmentTable) {

		appointmentTable.setNew(true);

		return appointmentTablePersistence.update(appointmentTable);
	}

	/**
	 * Creates a new appointment table with the primary key. Does not add the appointment table to the database.
	 *
	 * @param appointmentId the primary key for the new appointment table
	 * @return the new appointment table
	 */
	@Override
	@Transactional(enabled = false)
	public appointmentTable createappointmentTable(long appointmentId) {
		return appointmentTablePersistence.create(appointmentId);
	}

	/**
	 * Deletes the appointment table with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect appointmentTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param appointmentId the primary key of the appointment table
	 * @return the appointment table that was removed
	 * @throws PortalException if a appointment table with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public appointmentTable deleteappointmentTable(long appointmentId)
		throws PortalException {

		return appointmentTablePersistence.remove(appointmentId);
	}

	/**
	 * Deletes the appointment table from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect appointmentTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param appointmentTable the appointment table
	 * @return the appointment table that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public appointmentTable deleteappointmentTable(
		appointmentTable appointmentTable) {

		return appointmentTablePersistence.remove(appointmentTable);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return appointmentTablePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			appointmentTable.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return appointmentTablePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>Appointment_SchedulingDB.model.impl.appointmentTableModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return appointmentTablePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>Appointment_SchedulingDB.model.impl.appointmentTableModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return appointmentTablePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return appointmentTablePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return appointmentTablePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public appointmentTable fetchappointmentTable(long appointmentId) {
		return appointmentTablePersistence.fetchByPrimaryKey(appointmentId);
	}

	/**
	 * Returns the appointment table matching the UUID and group.
	 *
	 * @param uuid the appointment table's UUID
	 * @param groupId the primary key of the group
	 * @return the matching appointment table, or <code>null</code> if a matching appointment table could not be found
	 */
	@Override
	public appointmentTable fetchappointmentTableByUuidAndGroupId(
		String uuid, long groupId) {

		return appointmentTablePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the appointment table with the primary key.
	 *
	 * @param appointmentId the primary key of the appointment table
	 * @return the appointment table
	 * @throws PortalException if a appointment table with the primary key could not be found
	 */
	@Override
	public appointmentTable getappointmentTable(long appointmentId)
		throws PortalException {

		return appointmentTablePersistence.findByPrimaryKey(appointmentId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			appointmentTableLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(appointmentTable.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("appointmentId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			appointmentTableLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(appointmentTable.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"appointmentId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			appointmentTableLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(appointmentTable.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("appointmentId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<appointmentTable>() {

				@Override
				public void performAction(appointmentTable appointmentTable)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, appointmentTable);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(appointmentTable.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return appointmentTablePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement appointmentTableLocalServiceImpl#deleteappointmentTable(appointmentTable) to avoid orphaned data");
		}

		return appointmentTableLocalService.deleteappointmentTable(
			(appointmentTable)persistedModel);
	}

	@Override
	public BasePersistence<appointmentTable> getBasePersistence() {
		return appointmentTablePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return appointmentTablePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the appointment tables matching the UUID and company.
	 *
	 * @param uuid the UUID of the appointment tables
	 * @param companyId the primary key of the company
	 * @return the matching appointment tables, or an empty list if no matches were found
	 */
	@Override
	public List<appointmentTable> getappointmentTablesByUuidAndCompanyId(
		String uuid, long companyId) {

		return appointmentTablePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of appointment tables matching the UUID and company.
	 *
	 * @param uuid the UUID of the appointment tables
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of appointment tables
	 * @param end the upper bound of the range of appointment tables (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching appointment tables, or an empty list if no matches were found
	 */
	@Override
	public List<appointmentTable> getappointmentTablesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<appointmentTable> orderByComparator) {

		return appointmentTablePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the appointment table matching the UUID and group.
	 *
	 * @param uuid the appointment table's UUID
	 * @param groupId the primary key of the group
	 * @return the matching appointment table
	 * @throws PortalException if a matching appointment table could not be found
	 */
	@Override
	public appointmentTable getappointmentTableByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return appointmentTablePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the appointment tables.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>Appointment_SchedulingDB.model.impl.appointmentTableModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of appointment tables
	 * @param end the upper bound of the range of appointment tables (not inclusive)
	 * @return the range of appointment tables
	 */
	@Override
	public List<appointmentTable> getappointmentTables(int start, int end) {
		return appointmentTablePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of appointment tables.
	 *
	 * @return the number of appointment tables
	 */
	@Override
	public int getappointmentTablesCount() {
		return appointmentTablePersistence.countAll();
	}

	/**
	 * Updates the appointment table in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect appointmentTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param appointmentTable the appointment table
	 * @return the appointment table that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public appointmentTable updateappointmentTable(
		appointmentTable appointmentTable) {

		return appointmentTablePersistence.update(appointmentTable);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			appointmentTableLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		appointmentTableLocalService = (appointmentTableLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return appointmentTableLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return appointmentTable.class;
	}

	protected String getModelClassName() {
		return appointmentTable.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = appointmentTablePersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected appointmentTableLocalService appointmentTableLocalService;

	@Reference
	protected appointmentTablePersistence appointmentTablePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		appointmentTableLocalServiceBaseImpl.class);

}