/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ClgDB.model.impl;

import ClgDB.model.Clg_Table;

import ClgDB.service.Clg_TableLocalServiceUtil;

/**
 * The extended model base implementation for the Clg_Table service. Represents a row in the &quot;B_Clg_Table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Clg_TableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Clg_TableImpl
 * @see Clg_Table
 * @generated
 */
public abstract class Clg_TableBaseImpl
	extends Clg_TableModelImpl implements Clg_Table {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a clg_ table model instance should use the <code>Clg_Table</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Clg_TableLocalServiceUtil.addClg_Table(this);
		}
		else {
			Clg_TableLocalServiceUtil.updateClg_Table(this);
		}
	}

}