/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ClgDB.model.impl;

import ClgDB.model.Clg_Table;
import ClgDB.model.Clg_TableModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Clg_Table service. Represents a row in the &quot;B_Clg_Table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>Clg_TableModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Clg_TableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Clg_TableImpl
 * @generated
 */
@JSON(strict = true)
public class Clg_TableModelImpl
	extends BaseModelImpl<Clg_Table> implements Clg_TableModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a clg_ table model instance should use the <code>Clg_Table</code> interface instead.
	 */
	public static final String TABLE_NAME = "B_Clg_Table";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"ClgId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"address", Types.VARCHAR},
		{"age", Types.INTEGER}, {"dob", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ClgId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("age", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dob", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table B_Clg_Table (uuid_ VARCHAR(75) null,ClgId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,address VARCHAR(75) null,age INTEGER,dob DATE null)";

	public static final String TABLE_SQL_DROP = "drop table B_Clg_Table";

	public static final String ORDER_BY_JPQL = " ORDER BY clg_Table.name ASC";

	public static final String ORDER_BY_SQL = " ORDER BY B_Clg_Table.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public Clg_TableModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ClgId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setClgId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ClgId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Clg_Table.class;
	}

	@Override
	public String getModelClassName() {
		return Clg_Table.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Clg_Table, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Clg_Table, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Clg_Table, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Clg_Table)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Clg_Table, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Clg_Table, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Clg_Table)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Clg_Table, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Clg_Table, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Clg_Table, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Clg_Table, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Clg_Table, Object>>();

			attributeGetterFunctions.put("uuid", Clg_Table::getUuid);
			attributeGetterFunctions.put("ClgId", Clg_Table::getClgId);
			attributeGetterFunctions.put("groupId", Clg_Table::getGroupId);
			attributeGetterFunctions.put("companyId", Clg_Table::getCompanyId);
			attributeGetterFunctions.put("userId", Clg_Table::getUserId);
			attributeGetterFunctions.put("userName", Clg_Table::getUserName);
			attributeGetterFunctions.put(
				"createDate", Clg_Table::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Clg_Table::getModifiedDate);
			attributeGetterFunctions.put("name", Clg_Table::getName);
			attributeGetterFunctions.put("address", Clg_Table::getAddress);
			attributeGetterFunctions.put("age", Clg_Table::getAge);
			attributeGetterFunctions.put("dob", Clg_Table::getDob);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Clg_Table, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Clg_Table, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Clg_Table, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Clg_Table, String>)Clg_Table::setUuid);
			attributeSetterBiConsumers.put(
				"ClgId", (BiConsumer<Clg_Table, Long>)Clg_Table::setClgId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Clg_Table, Long>)Clg_Table::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Clg_Table, Long>)Clg_Table::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Clg_Table, Long>)Clg_Table::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Clg_Table, String>)Clg_Table::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Clg_Table, Date>)Clg_Table::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Clg_Table, Date>)Clg_Table::setModifiedDate);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<Clg_Table, String>)Clg_Table::setName);
			attributeSetterBiConsumers.put(
				"address",
				(BiConsumer<Clg_Table, String>)Clg_Table::setAddress);
			attributeSetterBiConsumers.put(
				"age", (BiConsumer<Clg_Table, Integer>)Clg_Table::setAge);
			attributeSetterBiConsumers.put(
				"dob", (BiConsumer<Clg_Table, Date>)Clg_Table::setDob);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getClgId() {
		return _ClgId;
	}

	@Override
	public void setClgId(long ClgId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ClgId = ClgId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@JSON
	@Override
	public int getAge() {
		return _age;
	}

	@Override
	public void setAge(int age) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_age = age;
	}

	@JSON
	@Override
	public Date getDob() {
		return _dob;
	}

	@Override
	public void setDob(Date dob) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dob = dob;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Clg_Table.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Clg_Table.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Clg_Table toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Clg_Table>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Clg_TableImpl clg_TableImpl = new Clg_TableImpl();

		clg_TableImpl.setUuid(getUuid());
		clg_TableImpl.setClgId(getClgId());
		clg_TableImpl.setGroupId(getGroupId());
		clg_TableImpl.setCompanyId(getCompanyId());
		clg_TableImpl.setUserId(getUserId());
		clg_TableImpl.setUserName(getUserName());
		clg_TableImpl.setCreateDate(getCreateDate());
		clg_TableImpl.setModifiedDate(getModifiedDate());
		clg_TableImpl.setName(getName());
		clg_TableImpl.setAddress(getAddress());
		clg_TableImpl.setAge(getAge());
		clg_TableImpl.setDob(getDob());

		clg_TableImpl.resetOriginalValues();

		return clg_TableImpl;
	}

	@Override
	public Clg_Table cloneWithOriginalValues() {
		Clg_TableImpl clg_TableImpl = new Clg_TableImpl();

		clg_TableImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		clg_TableImpl.setClgId(this.<Long>getColumnOriginalValue("ClgId"));
		clg_TableImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		clg_TableImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		clg_TableImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		clg_TableImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		clg_TableImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		clg_TableImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		clg_TableImpl.setName(this.<String>getColumnOriginalValue("name"));
		clg_TableImpl.setAddress(
			this.<String>getColumnOriginalValue("address"));
		clg_TableImpl.setAge(this.<Integer>getColumnOriginalValue("age"));
		clg_TableImpl.setDob(this.<Date>getColumnOriginalValue("dob"));

		return clg_TableImpl;
	}

	@Override
	public int compareTo(Clg_Table clg_Table) {
		int value = 0;

		value = getName().compareTo(clg_Table.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Clg_Table)) {
			return false;
		}

		Clg_Table clg_Table = (Clg_Table)object;

		long primaryKey = clg_Table.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Clg_Table> toCacheModel() {
		Clg_TableCacheModel clg_TableCacheModel = new Clg_TableCacheModel();

		clg_TableCacheModel.uuid = getUuid();

		String uuid = clg_TableCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			clg_TableCacheModel.uuid = null;
		}

		clg_TableCacheModel.ClgId = getClgId();

		clg_TableCacheModel.groupId = getGroupId();

		clg_TableCacheModel.companyId = getCompanyId();

		clg_TableCacheModel.userId = getUserId();

		clg_TableCacheModel.userName = getUserName();

		String userName = clg_TableCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			clg_TableCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			clg_TableCacheModel.createDate = createDate.getTime();
		}
		else {
			clg_TableCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			clg_TableCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			clg_TableCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		clg_TableCacheModel.name = getName();

		String name = clg_TableCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			clg_TableCacheModel.name = null;
		}

		clg_TableCacheModel.address = getAddress();

		String address = clg_TableCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			clg_TableCacheModel.address = null;
		}

		clg_TableCacheModel.age = getAge();

		Date dob = getDob();

		if (dob != null) {
			clg_TableCacheModel.dob = dob.getTime();
		}
		else {
			clg_TableCacheModel.dob = Long.MIN_VALUE;
		}

		return clg_TableCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Clg_Table, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Clg_Table, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Clg_Table, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Clg_Table)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Clg_Table>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Clg_Table.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _ClgId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _address;
	private int _age;
	private Date _dob;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Clg_Table, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Clg_Table)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("ClgId", _ClgId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("age", _age);
		_columnOriginalValues.put("dob", _dob);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("ClgId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("address", 512L);

		columnBitmasks.put("age", 1024L);

		columnBitmasks.put("dob", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Clg_Table _escapedModel;

}