/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Doctor_MgmtDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DoctorProfile service. Represents a row in the &quot;a_DoctorProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>Doctor_MgmtDB.model.impl.DoctorProfileModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>Doctor_MgmtDB.model.impl.DoctorProfileImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DoctorProfile
 * @generated
 */
@ProviderType
public interface DoctorProfileModel
	extends BaseModel<DoctorProfile>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a doctor profile model instance should use the {@link DoctorProfile} interface instead.
	 */

	/**
	 * Returns the primary key of this doctor profile.
	 *
	 * @return the primary key of this doctor profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this doctor profile.
	 *
	 * @param primaryKey the primary key of this doctor profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this doctor profile.
	 *
	 * @return the uuid of this doctor profile
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this doctor profile.
	 *
	 * @param uuid the uuid of this doctor profile
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the doctor ID of this doctor profile.
	 *
	 * @return the doctor ID of this doctor profile
	 */
	public long getDoctorId();

	/**
	 * Sets the doctor ID of this doctor profile.
	 *
	 * @param doctorId the doctor ID of this doctor profile
	 */
	public void setDoctorId(long doctorId);

	/**
	 * Returns the group ID of this doctor profile.
	 *
	 * @return the group ID of this doctor profile
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this doctor profile.
	 *
	 * @param groupId the group ID of this doctor profile
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this doctor profile.
	 *
	 * @return the company ID of this doctor profile
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this doctor profile.
	 *
	 * @param companyId the company ID of this doctor profile
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this doctor profile.
	 *
	 * @return the user ID of this doctor profile
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this doctor profile.
	 *
	 * @param userId the user ID of this doctor profile
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this doctor profile.
	 *
	 * @return the user uuid of this doctor profile
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this doctor profile.
	 *
	 * @param userUuid the user uuid of this doctor profile
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this doctor profile.
	 *
	 * @return the user name of this doctor profile
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this doctor profile.
	 *
	 * @param userName the user name of this doctor profile
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this doctor profile.
	 *
	 * @return the create date of this doctor profile
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this doctor profile.
	 *
	 * @param createDate the create date of this doctor profile
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this doctor profile.
	 *
	 * @return the modified date of this doctor profile
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this doctor profile.
	 *
	 * @param modifiedDate the modified date of this doctor profile
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this doctor profile.
	 *
	 * @return the name of this doctor profile
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this doctor profile.
	 *
	 * @param name the name of this doctor profile
	 */
	public void setName(String name);

	/**
	 * Returns the gender of this doctor profile.
	 *
	 * @return the gender of this doctor profile
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this doctor profile.
	 *
	 * @param gender the gender of this doctor profile
	 */
	public void setGender(String gender);

	/**
	 * Returns the dob of this doctor profile.
	 *
	 * @return the dob of this doctor profile
	 */
	public Date getDob();

	/**
	 * Sets the dob of this doctor profile.
	 *
	 * @param dob the dob of this doctor profile
	 */
	public void setDob(Date dob);

	/**
	 * Returns the email of this doctor profile.
	 *
	 * @return the email of this doctor profile
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this doctor profile.
	 *
	 * @param email the email of this doctor profile
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this doctor profile.
	 *
	 * @return the phone of this doctor profile
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this doctor profile.
	 *
	 * @param phone the phone of this doctor profile
	 */
	public void setPhone(String phone);

	/**
	 * Returns the image ID of this doctor profile.
	 *
	 * @return the image ID of this doctor profile
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this doctor profile.
	 *
	 * @param imageId the image ID of this doctor profile
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the specialization of this doctor profile.
	 *
	 * @return the specialization of this doctor profile
	 */
	@AutoEscape
	public String getSpecialization();

	/**
	 * Sets the specialization of this doctor profile.
	 *
	 * @param specialization the specialization of this doctor profile
	 */
	public void setSpecialization(String specialization);

	/**
	 * Returns the qualification of this doctor profile.
	 *
	 * @return the qualification of this doctor profile
	 */
	@AutoEscape
	public String getQualification();

	/**
	 * Sets the qualification of this doctor profile.
	 *
	 * @param qualification the qualification of this doctor profile
	 */
	public void setQualification(String qualification);

	/**
	 * Returns the experience years of this doctor profile.
	 *
	 * @return the experience years of this doctor profile
	 */
	public int getExperienceYears();

	/**
	 * Sets the experience years of this doctor profile.
	 *
	 * @param experienceYears the experience years of this doctor profile
	 */
	public void setExperienceYears(int experienceYears);

	/**
	 * Returns the languages of this doctor profile.
	 *
	 * @return the languages of this doctor profile
	 */
	@AutoEscape
	public String getLanguages();

	/**
	 * Sets the languages of this doctor profile.
	 *
	 * @param languages the languages of this doctor profile
	 */
	public void setLanguages(String languages);

	/**
	 * Returns the license number of this doctor profile.
	 *
	 * @return the license number of this doctor profile
	 */
	@AutoEscape
	public String getLicenseNumber();

	/**
	 * Sets the license number of this doctor profile.
	 *
	 * @param licenseNumber the license number of this doctor profile
	 */
	public void setLicenseNumber(String licenseNumber);

	/**
	 * Returns the available days of this doctor profile.
	 *
	 * @return the available days of this doctor profile
	 */
	@AutoEscape
	public String getAvailableDays();

	/**
	 * Sets the available days of this doctor profile.
	 *
	 * @param availableDays the available days of this doctor profile
	 */
	public void setAvailableDays(String availableDays);

	/**
	 * Returns the available time of this doctor profile.
	 *
	 * @return the available time of this doctor profile
	 */
	@AutoEscape
	public String getAvailableTime();

	/**
	 * Sets the available time of this doctor profile.
	 *
	 * @param availableTime the available time of this doctor profile
	 */
	public void setAvailableTime(String availableTime);

	/**
	 * Returns the hospital location of this doctor profile.
	 *
	 * @return the hospital location of this doctor profile
	 */
	@AutoEscape
	public String getHospitalLocation();

	/**
	 * Sets the hospital location of this doctor profile.
	 *
	 * @param hospitalLocation the hospital location of this doctor profile
	 */
	public void setHospitalLocation(String hospitalLocation);

	/**
	 * Returns the consultation mode of this doctor profile.
	 *
	 * @return the consultation mode of this doctor profile
	 */
	@AutoEscape
	public String getConsultationMode();

	/**
	 * Sets the consultation mode of this doctor profile.
	 *
	 * @param consultationMode the consultation mode of this doctor profile
	 */
	public void setConsultationMode(String consultationMode);

	/**
	 * Returns the address of this doctor profile.
	 *
	 * @return the address of this doctor profile
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this doctor profile.
	 *
	 * @param address the address of this doctor profile
	 */
	public void setAddress(String address);

	/**
	 * Returns the bio of this doctor profile.
	 *
	 * @return the bio of this doctor profile
	 */
	@AutoEscape
	public String getBio();

	/**
	 * Sets the bio of this doctor profile.
	 *
	 * @param bio the bio of this doctor profile
	 */
	public void setBio(String bio);

	/**
	 * Returns the fees of this doctor profile.
	 *
	 * @return the fees of this doctor profile
	 */
	public double getFees();

	/**
	 * Sets the fees of this doctor profile.
	 *
	 * @param fees the fees of this doctor profile
	 */
	public void setFees(double fees);

	/**
	 * Returns the rating of this doctor profile.
	 *
	 * @return the rating of this doctor profile
	 */
	public double getRating();

	/**
	 * Sets the rating of this doctor profile.
	 *
	 * @param rating the rating of this doctor profile
	 */
	public void setRating(double rating);

	@Override
	public DoctorProfile cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}